//------------------------------------------------------------------------------
// Copyright (c) 2005, 2006 IBM Corporation and others.
// All rights reserved. This program and the accompanying materials
// are made available under the terms of the Eclipse Public License v1.0
// which accompanies this distribution, and is available at
// http://www.eclipse.org/legal/epl-v10.html
// 
// Contributors:
// IBM Corporation - initial implementation
//------------------------------------------------------------------------------

// This file will include dynamically generated process layout related data from 
// the publishing service 
contentPage.processPage.imageFiles["_rpRBYZqjEdu6LZdnjUXiFAActivity"]="./../../govern.compliance/capabilitypatterns/resources/rcm_develop_controlled_work_product_4A2DAF36_4a2daf36_Activity.jpeg"
contentPage.processPage.imageFiles["__43k0dDdEdqLW8MRTbXhVQActivity"]="./../../govern.compliance/capabilitypatterns/resources/rcm_create_and_deploy_release_securely_5F49E939_5f49e939_Activity.jpeg"
contentPage.processPage.imageFiles["__43k0dDdEdqLW8MRTbXhVQ,_laFPsazVEdupW5-1VA4drg,_lwOiAKzZEdupW5-1VA4drgActivity"]="./../../govern.compliance/capabilitypatterns/resources/rcm_deliver_auditable_change_FF9EBC7A_83fdb7af_Activity.jpeg"
contentPage.processPage.imageFiles["__43k0dDdEdqLW8MRTbXhVQ,_bsya4NDiEdqLW8MRTbXhVQActivityDetail"]="./../../govern.compliance/capabilitypatterns/resources/Securely Deploy Release_3F0FD7F0_4874747d_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_GvpcAdAFEdqSo_AqzYf-hgActivity"]="./../../govern.compliance/capabilitypatterns/resources/rcm_deliver_auditable_change_F302CF_f302cf_Activity.jpeg"
contentPage.processPage.imageFiles["_GvpcAdAFEdqSo_AqzYf-hg,_ShQW9NAHEdqSo_AqzYf-hgActivityDetail"]="./../../govern.compliance/capabilitypatterns/resources/change_and_deliver_configuration_items_8ED37A1C_3ab34e3f_ActivityDetail.jpeg"
contentPage.processPage.elementUrls["_ShQW-9AHEdqSo_AqzYf-hg"] = ["Create Development Workspace","govern.compliance/capabilitypatterns/create_development_workspace_BA0DAA93.html"];
contentPage.processPage.elementUrls["_y6A6BNDjEdqLW8MRTbXhVQ"] = ["Release Notes","govern.compliance/capabilitypatterns/rup_release_notes_3771943C.html"];
contentPage.processPage.elementUrls["_TFFHBKzYEdupW5-1VA4drg"] = ["Conduct Review","govern.compliance/capabilitypatterns/conduct_review_BCDD9487.html"];
contentPage.processPage.elementUrls["_y6A6A9DjEdqLW8MRTbXhVQ"] = ["Installation Artifacts","govern.compliance/capabilitypatterns/rup_installation_artifacts_D4F07C08.html"];
contentPage.processPage.elementUrls["_ZY1faPbwEdyQp6WMO1mYBA"] = ["Development Process","govern.compliance/capabilitypatterns/rup_development_process_FDFC0277.html"];
contentPage.processPage.elementUrls["_UQ248fbwEdyQp6WMO1mYBA"] = ["Change Workflow Specification","govern.compliance/capabilitypatterns/rcm_change_workflow_specification_282E4D20.html"];
contentPage.processPage.elementUrls["_1nGcYZx4EduMOPYypke8PA"] = ["Iteration Plan","govern.compliance/capabilitypatterns/rup_iteration_plan_1C2A62CC.html"];
contentPage.processPage.elementUrls["_CwELkJqpEdu6LZdnjUXiFA"] = ["Approve Work Products","govern.compliance/capabilitypatterns/rcm_approve_work_products_180794E7.html"];
contentPage.processPage.elementUrls["_ShQW8NAHEdqSo_AqzYf-hg"] = ["Any Role","govern.compliance/capabilitypatterns/rup_any_role_CA4197FD.html"];
contentPage.processPage.elementUrls["_Ot-vVJx7EduMOPYypke8PA"] = ["Baseline","govern.compliance/capabilitypatterns/rcm_baseline_9DE03677.html"];
contentPage.processPage.elementUrls["_yIFzZazVEdupW5-1VA4drg"] = ["Software Development Plan","govern.compliance/capabilitypatterns/rup_project_plan_CDF78DF2.html"];
contentPage.processPage.elementUrls["_z5WVo6zVEdupW5-1VA4drg"] = ["Baseline Control Point","govern.compliance/capabilitypatterns/rcm_baseline_control_point_61C2DA08.html"];
contentPage.processPage.elementUrls["_yxVSzazXEdupW5-1VA4drg"] = ["Configuration Audit Findings","govern.compliance/capabilitypatterns/rup_configuration_audit_findings_89283A8C.html"];
contentPage.processPage.elementUrls["_CjNwsJx9EduMOPYypke8PA"] = ["Product","govern.compliance/capabilitypatterns/rup_product_736655FE.html"];
contentPage.processPage.elementUrls["_yxVSxazXEdupW5-1VA4drg"] = ["Establish Configuration Management (CM) Policies","govern.compliance/capabilitypatterns/establish_project_cm_policies_4764E.html"];
contentPage.processPage.elementUrls["_9FxUcKUrEduzFIHfR8n_8Q"] = ["Conduct Review","govern.compliance/capabilitypatterns/conduct_review_CDC56263.html"];
contentPage.processPage.elementUrls["_twICgKyyEdupW5-1VA4drg"] = ["Work Product Approval","govern.compliance/capabilitypatterns/rcm_work_product_approval_6C5E992C.html"];
contentPage.processPage.elementUrls["_ShQW-NAHEdqSo_AqzYf-hg"] = ["Integrator","govern.compliance/capabilitypatterns/rup_integrator_57FCE0A8.html"];
contentPage.processPage.elementUrls["_yIFzYazVEdupW5-1VA4drg"] = ["Integrator","govern.compliance/capabilitypatterns/rup_integrator_965ABD3.html"];
contentPage.processPage.elementUrls["_z5WVoqzVEdupW5-1VA4drg"] = ["Baseline","govern.compliance/capabilitypatterns/rcm_baseline_F8E90443.html"];
contentPage.processPage.elementUrls["_lwOiAKzZEdupW5-1VA4drg"] = ["Deliver Auditable Change","govern.compliance/capabilitypatterns/rcm_deliver_auditable_change_FF9EBC7A.html"];
contentPage.processPage.elementUrls["_laFPsazVEdupW5-1VA4drg"] = ["Create the software release","govern.compliance/capabilitypatterns/Create Software Release_9BCF2354.html"];
contentPage.processPage.elementUrls["_yxVSyKzXEdupW5-1VA4drg"] = ["Establish Change Control Process","govern.compliance/capabilitypatterns/establish_project_change_control_process_D5FD4457.html"];
contentPage.processPage.elementUrls["_y53JANDjEdqLW8MRTbXhVQ"] = ["Create Deployment Unit","govern.compliance/capabilitypatterns/create_deployment_unit_CCBCA67E.html"];
contentPage.processPage.elementUrls["_y6A6B9DjEdqLW8MRTbXhVQ"] = ["Deployment Model","govern.compliance/capabilitypatterns/rup_deployment_model_99825E27.html"];
contentPage.processPage.elementUrls["_8moaUZx4EduMOPYypke8PA"] = ["Reviewer","govern.compliance/capabilitypatterns/rup_reviewer_40E6BA7E.html"];
contentPage.processPage.elementUrls["__43k0dDdEdqLW8MRTbXhVQ"] = ["Create and Deploy the Release Securely","govern.compliance/capabilitypatterns/rcm_create_and_deploy_release_securely_5F49E939.html"];
contentPage.processPage.elementUrls["_8pCXtKzXEdupW5-1VA4drg"] = ["Distribution Policy","govern.compliance/capabilitypatterns/rcm_distribution_policy_45B8CB0D.html"];
contentPage.processPage.elementUrls["_5KQwEdDjEdqLW8MRTbXhVQ"] = ["Release Manager","govern.compliance/capabilitypatterns/rcm_release_manager_732717F9.html"];
contentPage.processPage.elementUrls["_TFFG96zYEdupW5-1VA4drg"] = ["Risk Management Plan","govern.compliance/capabilitypatterns/rup_risk_management_plan_6823099A.html"];
contentPage.processPage.elementUrls["_ZY1fZvbwEdyQp6WMO1mYBA"] = ["Project-Specific Guidelines","govern.compliance/capabilitypatterns/rup_project_specific_guidelines_9735C7C4.html"];
contentPage.processPage.elementUrls["_TFFG_6zYEdupW5-1VA4drg"] = ["Configuration Management Plan","govern.compliance/capabilitypatterns/rup_cm_plan_95CA9A34.html"];
contentPage.processPage.elementUrls["_y6A6AdDjEdqLW8MRTbXhVQ"] = ["Deployment Plan","govern.compliance/capabilitypatterns/rup_deployment_plan_6178C633.html"];
contentPage.processPage.elementUrls["_yxVSx6zXEdupW5-1VA4drg"] = ["Write Configuration Management (CM) Plan","govern.compliance/capabilitypatterns/write_cm_plan_737C2C23.html"];
contentPage.processPage.elementUrls["_y6A6CNDjEdqLW8MRTbXhVQ"] = ["User Support Material","govern.compliance/capabilitypatterns/rup_support_material_FC03765B.html"];
contentPage.processPage.elementUrls["_yxVSxKzXEdupW5-1VA4drg"] = ["Configuration Manager","govern.compliance/capabilitypatterns/rup_configuration_manager_116B6238.html"];
contentPage.processPage.elementUrls["_yIFzYqzVEdupW5-1VA4drg"] = ["Project Repository","govern.compliance/capabilitypatterns/rup_project_repository_14038BE3.html"];
contentPage.processPage.elementUrls["_ZY1fa_bwEdyQp6WMO1mYBA"] = ["Change Control Point","govern.compliance/capabilitypatterns/rcm_change_control_point_B7F00486.html"];
contentPage.processPage.elementUrls["_Ot-vVZx7EduMOPYypke8PA"] = ["Change Control Point","govern.compliance/capabilitypatterns/rcm_change_control_point_A87E1687.html"];
contentPage.processPage.elementUrls["_ZY1fZ_bwEdyQp6WMO1mYBA"] = ["Software Development Plan","govern.compliance/capabilitypatterns/rup_project_plan_57F2D5AD.html"];
contentPage.processPage.elementUrls["_mf7I8aUrEduzFIHfR8n_8Q"] = ["Apply Control","govern.compliance/capabilitypatterns/Assess changes_2A121085.html"];
contentPage.processPage.elementUrls["_89AB4NDjEdqLW8MRTbXhVQ"] = ["Distribute Software Release","govern.compliance/capabilitypatterns/rcm_distribute_software_release_194A49BA.html"];
contentPage.processPage.elementUrls["_d1J5sfbwEdyQp6WMO1mYBA"] = ["Software Development Plan","govern.compliance/capabilitypatterns/rup_project_plan_495B241F.html"];
contentPage.processPage.elementUrls["_TFFG8KzYEdupW5-1VA4drg"] = ["Issues List","govern.compliance/capabilitypatterns/rup_issues_list_41805D90.html"];
contentPage.processPage.elementUrls["_UQ248PbwEdyQp6WMO1mYBA"] = ["Control Point Specification","govern.compliance/capabilitypatterns/rcm_control_point_specification_3995390A.html"];
contentPage.processPage.elementUrls["_d1J5svbwEdyQp6WMO1mYBA"] = ["Development Process","govern.compliance/capabilitypatterns/rup_development_process_53F9042F.html"];
contentPage.processPage.elementUrls["_rpRBYZqjEdu6LZdnjUXiFA"] = ["Develop a Controlled Work Product","govern.compliance/capabilitypatterns/rcm_develop_controlled_work_product_4A2DAF36.html"];
contentPage.processPage.elementUrls["_TFFG8azYEdupW5-1VA4drg"] = ["Problem Resolution Plan","govern.compliance/capabilitypatterns/rup_problem_resolution_plan_301971A6.html"];
contentPage.processPage.elementUrls["_8pCXs6zXEdupW5-1VA4drg"] = ["Supplementary Specifications","govern.compliance/capabilitypatterns/rup_supplementary_specification_E337B2D9.html"];
contentPage.processPage.elementUrls["_z5WVoKzVEdupW5-1VA4drg"] = ["Approve Baseline","govern.compliance/capabilitypatterns/rcm_approve_baseline_FFB2101D.html"];
contentPage.processPage.elementUrls["_ZY1favbwEdyQp6WMO1mYBA"] = ["Baseline","govern.compliance/capabilitypatterns/rcm_baseline_F732F69D.html"];
contentPage.processPage.elementUrls["_ZY1fYfbwEdyQp6WMO1mYBA"] = ["Reviewer","govern.compliance/capabilitypatterns/rup_reviewer_C8060595.html"];
contentPage.processPage.elementUrls["_UlbawPbwEdyQp6WMO1mYBA"] = ["Project-Specific Guidelines","govern.compliance/capabilitypatterns/rup_project_specific_guidelines_82E92403.html"];
contentPage.processPage.elementUrls["_1nGcYJx4EduMOPYypke8PA"] = ["Review Coordinator","govern.compliance/capabilitypatterns/rup_review_manager_118C82BC.html"];
contentPage.processPage.elementUrls["_uSa0EKyuEdupW5-1VA4drg"] = ["Controlled work product","govern.compliance/capabilitypatterns/Controlled Work Product_1E1AF41A.html"];
contentPage.processPage.elementUrls["_y53JAdDjEdqLW8MRTbXhVQ"] = ["Configuration Manager","govern.compliance/capabilitypatterns/rup_configuration_manager_BB55BA94.html"];
contentPage.processPage.elementUrls["_yxVSyqzXEdupW5-1VA4drg"] = ["Development Infrastructure","govern.compliance/capabilitypatterns/rup_development_infrastructure_CF34387D.html"];
contentPage.processPage.elementUrls["_1nGcY5x4EduMOPYypke8PA"] = ["Development Process","govern.compliance/capabilitypatterns/rup_development_process_739D4CA7.html"];
contentPage.processPage.elementUrls["_5KZ6AdDjEdqLW8MRTbXhVQ"] = ["Distribution Policy","govern.compliance/capabilitypatterns/rcm_distribution_policy_4D4D46D3.html"];
contentPage.processPage.elementUrls["_yIFzY6zVEdupW5-1VA4drg"] = ["Workspace","govern.compliance/capabilitypatterns/rup_workspace_7CDD61A8.html"];
contentPage.processPage.elementUrls["_yxVSw6zXEdupW5-1VA4drg"] = ["Configuration Management Plan","govern.compliance/capabilitypatterns/rup_cm_plan_AEEA4A04.html"];
contentPage.processPage.elementUrls["_Ot-vU5x7EduMOPYypke8PA"] = ["Technical Lead","govern.compliance/capabilitypatterns/rcm_technical_lead_3B5F1E43.html"];
contentPage.processPage.elementUrls["_TFFG_KzYEdupW5-1VA4drg"] = ["Monitor Project Status","govern.compliance/capabilitypatterns/monitor_project_status_33B9D049.html"];
contentPage.processPage.elementUrls["_TFFG-qzYEdupW5-1VA4drg"] = ["Schedule and Assign Work","govern.compliance/capabilitypatterns/schedule_and_assign_work_C8729A61.html"];
contentPage.processPage.elementUrls["_TFFHBqzYEdupW5-1VA4drg"] = ["Business Case","govern.compliance/capabilitypatterns/rup_business_case_B61488AD.html"];
contentPage.processPage.elementUrls["_7bZsQtDjEdqLW8MRTbXhVQ"] = ["Release Control Point","govern.compliance/capabilitypatterns/rcm_release_control_point_D16C17A5.html"];
contentPage.processPage.elementUrls["_0VZ_UKywEdupW5-1VA4drg"] = ["Develop Work Product","govern.compliance/capabilitypatterns/rcm_develop_work_products_6B8A940A.html"];
contentPage.processPage.elementUrls["_W-1SVJqmEdu6LZdnjUXiFA"] = ["Project-Specific Guidelines","govern.compliance/capabilitypatterns/rup_project_specific_guidelines_4FBD5396.html"];
contentPage.processPage.elementUrls["_1nGcYpx4EduMOPYypke8PA"] = ["Review Record","govern.compliance/capabilitypatterns/rup_review_record_AC376E2.html"];
contentPage.processPage.elementUrls["_TFFHAqzYEdupW5-1VA4drg"] = ["Organize Review","govern.compliance/capabilitypatterns/organize_review_F182A68E.html"];
contentPage.processPage.elementUrls["_zOjhcKyvEdupW5-1VA4drg"] = ["Performer (supportive)","govern.compliance/capabilitypatterns/rcm_performer_113D98A3.html"];
contentPage.processPage.elementUrls["_UcL_MPbwEdyQp6WMO1mYBA"] = ["Configuration Audit Findings","govern.compliance/capabilitypatterns/rup_configuration_audit_findings_4E5C39B8.html"];
contentPage.processPage.elementUrls["_8pCXsKzXEdupW5-1VA4drg"] = ["Define Distribution Policy","govern.compliance/capabilitypatterns/rcm_define_distribution_policy_8126E8EE.html"];
contentPage.processPage.elementUrls["_Ug9KcPbwEdyQp6WMO1mYBA"] = ["Project-Specific Guidelines","govern.compliance/capabilitypatterns/rup_project_specific_guidelines_22F6F245.html"];
contentPage.processPage.elementUrls["_TFFG_azYEdupW5-1VA4drg"] = ["Report Status","govern.compliance/capabilitypatterns/report_status_2252E45F.html"];
contentPage.processPage.elementUrls["_yxVSwqzXEdupW5-1VA4drg"] = ["Software Development Plan","govern.compliance/capabilitypatterns/rup_project_plan_4610743F.html"];
contentPage.processPage.elementUrls["_89Jy4NDjEdqLW8MRTbXhVQ"] = ["Deployment Manager","govern.compliance/capabilitypatterns/rup_deployment_manager_6D95D388.html"];
contentPage.processPage.elementUrls["_KEVmYKywEdupW5-1VA4drg"] = ["Informed (Set of Informed Roles)","govern.compliance/capabilitypatterns/rcm_informed_788E7CCC.html"];
contentPage.processPage.elementUrls["_7bZsQNDjEdqLW8MRTbXhVQ"] = ["Test Results Approval","govern.compliance/capabilitypatterns/rcm_test_results_approval_D835237F.html"];
contentPage.processPage.elementUrls["_TFFG-6zYEdupW5-1VA4drg"] = ["Change Request","govern.compliance/capabilitypatterns/rup_change_request_314C7026.html"];
contentPage.processPage.elementUrls["_ZY1fY_bwEdyQp6WMO1mYBA"] = ["Integrator","govern.compliance/capabilitypatterns/rup_integrator_9360F38E.html"];
contentPage.processPage.elementUrls["_TFFG9azYEdupW5-1VA4drg"] = ["Software Development Plan","govern.compliance/capabilitypatterns/rup_project_plan_F4AB53C5.html"];
contentPage.processPage.elementUrls["_ShQW99AHEdqSo_AqzYf-hg"] = ["Integration Build Plan","govern.compliance/capabilitypatterns/rup_integration_build_plan_F0E44407.html"];
contentPage.processPage.elementUrls["_bsya4NDiEdqLW8MRTbXhVQ"] = ["Securely Deploy the Release","govern.compliance/capabilitypatterns/Securely Deploy Release_3F0FD7F0.html"];
contentPage.processPage.elementUrls["_y6A6BtDjEdqLW8MRTbXhVQ"] = ["Project Repository","govern.compliance/capabilitypatterns/rup_project_repository_30A88862.html"];
contentPage.processPage.elementUrls["_y6A6ANDjEdqLW8MRTbXhVQ"] = ["Build","govern.compliance/capabilitypatterns/rup_build_72DFB21D.html"];
contentPage.processPage.elementUrls["_TE_AU6zYEdupW5-1VA4drg"] = ["Review Record","govern.compliance/capabilitypatterns/rup_review_record_A84E743E.html"];
contentPage.processPage.elementUrls["_ShQW_dAHEdqSo_AqzYf-hg"] = ["Deliver Changes","govern.compliance/capabilitypatterns/deliver_changes_AB141ECC.html"];
contentPage.processPage.elementUrls["_8pCXsqzXEdupW5-1VA4drg"] = ["Deployment Plan","govern.compliance/capabilitypatterns/rup_deployment_plan_7A5DDD14.html"];
contentPage.processPage.elementUrls["_ZY1fbPbwEdyQp6WMO1mYBA"] = ["Workspace","govern.compliance/capabilitypatterns/rup_workspace_C28DE496.html"];
contentPage.processPage.elementUrls["_5KZ6ANDjEdqLW8MRTbXhVQ"] = ["Supplementary Specifications","govern.compliance/capabilitypatterns/rup_supplementary_specification_5EB432BD.html"];
contentPage.processPage.elementUrls["_ShQW_NAHEdqSo_AqzYf-hg"] = ["Workspace","govern.compliance/capabilitypatterns/rup_workspace_BC7B0AB6.html"];
contentPage.processPage.elementUrls["_y6A6CdDjEdqLW8MRTbXhVQ"] = ["Deployment Unit","govern.compliance/capabilitypatterns/rup_deployment_unit_EA9C8A71.html"];
contentPage.processPage.elementUrls["_ShHNAtAHEdqSo_AqzYf-hg"] = ["Project Repository","govern.compliance/capabilitypatterns/rup_project_repository_4CEB861A.html"];
contentPage.processPage.elementUrls["_TFFG8qzYEdupW5-1VA4drg"] = ["Work Order","govern.compliance/capabilitypatterns/rup_work_order_3AB751B6.html"];
contentPage.processPage.elementUrls["_TE_AVKzYEdupW5-1VA4drg"] = ["Project Manager","govern.compliance/capabilitypatterns/rup_project_manager_ACF8C72.html"];
contentPage.processPage.elementUrls["_ZY1fYPbwEdyQp6WMO1mYBA"] = ["Review Coordinator","govern.compliance/capabilitypatterns/rup_review_manager_D96CF17F.html"];
contentPage.processPage.elementUrls["_Z56jYZqmEdu6LZdnjUXiFA"] = ["Reviewer","govern.compliance/capabilitypatterns/rup_reviewer_A0E1AE1A.html"];
contentPage.processPage.elementUrls["_0v7YUKzVEdupW5-1VA4drg"] = ["Promote Baselines","govern.compliance/capabilitypatterns/promote_baseline_CDD3D625.html"];
contentPage.processPage.elementUrls["_TFFHA6zYEdupW5-1VA4drg"] = ["Review Coordinator","govern.compliance/capabilitypatterns/rup_review_manager_5A5C7C53.html"];
contentPage.processPage.elementUrls["_7bGKQNDjEdqLW8MRTbXhVQ"] = ["Approve Product Distribution","govern.compliance/capabilitypatterns/rcm_approve_product_distribution_8492F44A.html"];
contentPage.processPage.elementUrls["_tZ5bMKyvEdupW5-1VA4drg"] = ["Technical Authority (Responsible)","govern.compliance/capabilitypatterns/rcm_technical_authority_C9A4AA99.html"];
contentPage.processPage.elementUrls["_d1J5sPbwEdyQp6WMO1mYBA"] = ["Iteration Plan","govern.compliance/capabilitypatterns/rup_iteration_plan_5AC21009.html"];
contentPage.processPage.elementUrls["_z5WVoazVEdupW5-1VA4drg"] = ["Release Manager","govern.compliance/capabilitypatterns/rcm_release_manager_EE4B2433.html"];
contentPage.processPage.elementUrls["_yIFzZqzVEdupW5-1VA4drg"] = ["Project-Specific Guidelines","govern.compliance/capabilitypatterns/rup_project_specific_guidelines_D8956E02.html"];
contentPage.processPage.elementUrls["_yxVSwazXEdupW5-1VA4drg"] = ["Plan the Project Configuration and Change Control","govern.compliance/capabilitypatterns/plan_project_configuration_change_control_3B72942F.html"];
contentPage.processPage.elementUrls["_ShHNAdAHEdqSo_AqzYf-hg"] = ["Work Order","govern.compliance/capabilitypatterns/rup_work_order_424DA60A.html"];
contentPage.processPage.elementUrls["_ZY1fZPbwEdyQp6WMO1mYBA"] = ["Iteration Plan","govern.compliance/capabilitypatterns/rup_iteration_plan_9DFED39E.html"];
contentPage.processPage.elementUrls["_ZY1fafbwEdyQp6WMO1mYBA"] = ["Project Repository","govern.compliance/capabilitypatterns/rup_project_repository_EC95168D.html"];
contentPage.processPage.elementUrls["_TFFG9qzYEdupW5-1VA4drg"] = ["Iteration Plan","govern.compliance/capabilitypatterns/rup_iteration_plan_FF4933D5.html"];
contentPage.processPage.elementUrls["_iy8EcZqkEdu6LZdnjUXiFA"] = ["Finalize work product","govern.compliance/capabilitypatterns/rcm_finalize_work_product_EAF8603C.html"];
contentPage.processPage.elementUrls["_A9lTgKUsEduzFIHfR8n_8Q"] = ["Approve Delivered Changes","govern.compliance/capabilitypatterns/rcm_approve_delivered_changes_21114456.html"];
contentPage.processPage.elementUrls["_TFFG_qzYEdupW5-1VA4drg"] = ["Handle Exceptions and Problems","govern.compliance/capabilitypatterns/handle_exceptions_and_problems_2CF0C46F.html"];
contentPage.processPage.elementUrls["_ZY1fYvbwEdyQp6WMO1mYBA"] = ["Technical Lead","govern.compliance/capabilitypatterns/rcm_technical_lead_D2A3E5A5.html"];
contentPage.processPage.elementUrls["_y6A6AtDjEdqLW8MRTbXhVQ"] = ["Bill of Materials","govern.compliance/capabilitypatterns/rup_bill_of_materials_6C16A643.html"];
contentPage.processPage.elementUrls["_UWYSIfbwEdyQp6WMO1mYBA"] = ["Control Point Specification","govern.compliance/capabilitypatterns/rcm_control_point_specification_B2BD910D.html"];
contentPage.processPage.elementUrls["_ShQW9tAHEdqSo_AqzYf-hg"] = ["Software Development Plan","govern.compliance/capabilitypatterns/rup_project_plan_880A6E42.html"];
contentPage.processPage.elementUrls["_TFFG86zYEdupW5-1VA4drg"] = ["Project Measurements","govern.compliance/capabilitypatterns/rup_project_measurements_A391277B.html"];
contentPage.processPage.elementUrls["_TFFHB6zYEdupW5-1VA4drg"] = ["Iteration Assessment","govern.compliance/capabilitypatterns/rup_iteration_assessment_1EEE5E72.html"];
contentPage.processPage.elementUrls["_TzHPIZqkEdu6LZdnjUXiFA"] = ["Create Work Product","govern.compliance/capabilitypatterns/rcm_create_work_product_4837A8C7.html"];
contentPage.processPage.elementUrls["_TE_AUqzYEdupW5-1VA4drg"] = ["Status Assessment","govern.compliance/capabilitypatterns/rup_status_assessment_3F749E79.html"];
contentPage.processPage.elementUrls["_Z56jYJqmEdu6LZdnjUXiFA"] = ["Conduct Review","govern.compliance/capabilitypatterns/conduct_review_9643CE0A.html"];
contentPage.processPage.elementUrls["_ShHNA9AHEdqSo_AqzYf-hg"] = ["Update Workspace","govern.compliance/capabilitypatterns/update_workspace_B5C55BDF.html"];
contentPage.processPage.elementUrls["_UWYSIPbwEdyQp6WMO1mYBA"] = ["Change Workflow Specification","govern.compliance/capabilitypatterns/rcm_change_workflow_specification_C4247CF7.html"];
contentPage.processPage.elementUrls["_ShQW9dAHEdqSo_AqzYf-hg"] = ["Project-Specific Guidelines","govern.compliance/capabilitypatterns/rup_project_specific_guidelines_7D6C8E32.html"];
contentPage.processPage.elementUrls["_yIFzYKzVEdupW5-1VA4drg"] = ["Create Baselines","govern.compliance/capabilitypatterns/create_baseline_1ACC97BD.html"];
contentPage.processPage.elementUrls["_W-1SUJqmEdu6LZdnjUXiFA"] = ["Organize Review","govern.compliance/capabilitypatterns/organize_review_8B2B7177.html"];
contentPage.processPage.elementUrls["_y6A6BdDjEdqLW8MRTbXhVQ"] = ["Training Materials","govern.compliance/capabilitypatterns/rup_training_materials_260AA852.html"];
contentPage.processPage.elementUrls["_TFFHBazYEdupW5-1VA4drg"] = ["Reviewer","govern.compliance/capabilitypatterns/rup_reviewer_AB76A89D.html"];
contentPage.processPage.elementUrls["_SZYlwKywEdupW5-1VA4drg"] = ["Consulted (Set of Consulted Roles)","govern.compliance/capabilitypatterns/rcm_consulted_A79C1657.html"];
contentPage.processPage.elementUrls["_57MYkKyvEdupW5-1VA4drg"] = ["Managerial Authority (Accountable)","govern.compliance/capabilitypatterns/rcm_managerial_authority_7B195596.html"];
contentPage.processPage.elementUrls["_yIFzZKzVEdupW5-1VA4drg"] = ["Work Order","govern.compliance/capabilitypatterns/rup_work_order_DF5E79DC.html"];
contentPage.processPage.elementUrls["_ShQW9NAHEdqSo_AqzYf-hg"] = ["Change and Deliver Configuration Items","govern.compliance/capabilitypatterns/change_and_deliver_configuration_items_8ED37A1C.html"];
contentPage.processPage.elementUrls["_ds-H8KyyEdupW5-1VA4drg"] = ["Review Record","govern.compliance/capabilitypatterns/rup_review_record_69770BE8.html"];
contentPage.processPage.elementUrls["_3SLlMKUrEduzFIHfR8n_8Q"] = ["Organize Review","govern.compliance/capabilitypatterns/organize_review_105BFB8F.html"];
contentPage.processPage.elementUrls["_TFFG-azYEdupW5-1VA4drg"] = ["Development Process","govern.compliance/capabilitypatterns/rup_development_process_BDD4BA51.html"];
contentPage.processPage.elementUrls["_TFFG9KzYEdupW5-1VA4drg"] = ["Risk List","govern.compliance/capabilitypatterns/rup_risk_list_6123FAF.html"];
contentPage.processPage.elementUrls["_bvlEgJqmEdu6LZdnjUXiFA"] = ["Address Review Comments","govern.compliance/capabilitypatterns/rcm_address_review_comments_DFC56D9A.html"];
contentPage.processPage.elementUrls["_GvpcAdAFEdqSo_AqzYf-hg"] = ["Deliver Auditable Change","govern.compliance/capabilitypatterns/rcm_deliver_auditable_change_F302CF.html"];
contentPage.processPage.elementUrls["_yxVSy6zXEdupW5-1VA4drg"] = ["Project Repository","govern.compliance/capabilitypatterns/rup_project_repository_380E0E42.html"];
contentPage.processPage.elementUrls["_TE_AUazYEdupW5-1VA4drg"] = ["Monitor and Control the Project","govern.compliance/capabilitypatterns/monitor_control_project_34D6BE69.html"];
contentPage.processPage.elementUrls["_TFFHAazYEdupW5-1VA4drg"] = ["Management Reviewer","govern.compliance/capabilitypatterns/rup_management_reviewer_E6E4C67E.html"];
contentPage.processPage.elementUrls["_ShQW8tAHEdqSo_AqzYf-hg"] = ["Make Changes","govern.compliance/capabilitypatterns/make_changes_to_configuration_items_C3788C23.html"];
contentPage.processPage.elementUrls["_ZY1fZfbwEdyQp6WMO1mYBA"] = ["Review Record","govern.compliance/capabilitypatterns/rup_review_record_8C97E7B4.html"];
contentPage.processPage.elementUrls["_TFFG-KzYEdupW5-1VA4drg"] = ["Measurement Plan","govern.compliance/capabilitypatterns/rup_measurement_plan_CF3BA63B.html"];
contentPage.processPage.elementUrls["_0wBe8KzVEdupW5-1VA4drg"] = ["Technical Lead","govern.compliance/capabilitypatterns/rcm_technical_lead_2DD6F944.html"];
contentPage.processPage.elementUrls["_TFFHAKzYEdupW5-1VA4drg"] = ["Project Review Authority (PRA) Project Review","govern.compliance/capabilitypatterns/pra_project_review_F84BB268.html"];
contentPage.processPage.elementUrls["_yxVSxqzXEdupW5-1VA4drg"] = ["Development Process","govern.compliance/capabilitypatterns/rup_development_process_AA2565E.html"];
contentPage.processPage.elementUrls["_yxVSyazXEdupW5-1VA4drg"] = ["Change Control Manager","govern.compliance/capabilitypatterns/rup_change_manager_C496586D.html"];
contentPage.processPage.elementUrls["_W-1SUZqmEdu6LZdnjUXiFA"] = ["Review Coordinator","govern.compliance/capabilitypatterns/rup_review_manager_95C95187.html"];
contentPage.processPage.elementUrls["_8pCXsazXEdupW5-1VA4drg"] = ["Release Manager","govern.compliance/capabilitypatterns/rcm_release_manager_6FBFFD04.html"];
contentPage.processPage.elementUrls["_ZildEKywEdupW5-1VA4drg"] = ["Reviewer","govern.compliance/capabilitypatterns/rup_reviewer_716C4436.html"];
contentPage.processPage.elementUrls["_W-1SU5qmEdu6LZdnjUXiFA"] = ["Review Record","govern.compliance/capabilitypatterns/rup_review_record_ED3C3B62.html"];
contentPage.processPage.elementUrls["_ShQW8dAHEdqSo_AqzYf-hg"] = ["Build","govern.compliance/capabilitypatterns/rup_build_B8DAAC13.html"];
contentPage.processPage.elementUrls["_fnk7sZqkEdu6LZdnjUXiFA"] = ["Review Work Product","govern.compliance/capabilitypatterns/rcm_review_work_product_FBDF2223.html"];
contentPage.processPage.elementUrls["_xVDfcKUrEduzFIHfR8n_8Q"] = ["Promote Baselines","govern.compliance/capabilitypatterns/promote_baseline_4DAE9A19.html"];
contentPage.processPage.elementUrls["_yxVSzKzXEdupW5-1VA4drg"] = ["Change Request","govern.compliance/capabilitypatterns/rup_change_request_9A8F2676.html"];
contentPage.processPage.elementUrls["_TFFHCKzYEdupW5-1VA4drg"] = ["Technical Lead","govern.compliance/capabilitypatterns/rcm_technical_lead_816F76A6.html"];
