//------------------------------------------------------------------------------
// Copyright (c) 2005, 2006 IBM Corporation and others.
// All rights reserved. This program and the accompanying materials
// are made available under the terms of the Eclipse Public License v1.0
// which accompanies this distribution, and is available at
// http://www.eclipse.org/legal/epl-v10.html
// 
// Contributors:
// IBM Corporation - initial implementation
//------------------------------------------------------------------------------

// This file will include dynamically generated process layout related data from 
// the publishing service 
contentPage.processPage.imageFiles["_Fnf5YRsYEd6iF4LVaEfgRw,_GNDgtxscEd6iF4LVaEfgRwActivity"]="./../../practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/resources/define_and_prioritize_portfolio_D7AA1C51_730f9e6e_Activity.jpeg"
contentPage.processPage.imageFiles["_Fnf5YRsYEd6iF4LVaEfgRwActivity"]="./../../practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/resources/prod_portf_mgmt_reference_model_454E7EC9_454e7ec9_Activity.jpeg"
contentPage.processPage.imageFiles["_Fnf5YRsYEd6iF4LVaEfgRw,_Hn861DA4Ed6dhLmEQKbzPgActivity"]="./../../practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/resources/define_portfolio_structures_and_metrics_8B1CE95B_26826b78_Activity.jpeg"
contentPage.processPage.imageFiles["_Fnf5YRsYEd6iF4LVaEfgRw,_N8IFMBscEd6iF4LVaEfgRwActivity"]="./../../practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/resources/balance_and_authorize_portfolio_7D516C9F_18b6eebc_Activity.jpeg"
contentPage.processPage.imageFiles["_Fnf5YRsYEd6iF4LVaEfgRw,_OzHXkBscEd6iF4LVaEfgRwActivity"]="./../../practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/resources/monitor_and_control_portfolio_DAB7FB55_761d7d72_Activity.jpeg"
contentPage.processPage.imageFiles["_8IT7Ef7cEd2qlKqF0pYYYg,_72MGwRTJEd6-CtZFHiHFGAActivity"]="./../../practice.mgmt.portfolio_mgmt.base-ibm/deliveryprocesses/resources/balance_and_authorize_portfolio_4135AB31_afe6b8c5_Activity.jpeg"
contentPage.processPage.suppressedItems["_8IT7Ef7cEd2qlKqF0pYYYg,_72MGwRTJEd6-CtZFHiHFGA,_qPzHADtZEd6EJ5PABot5eA"]=true
contentPage.processPage.suppressedItems["_8IT7Ef7cEd2qlKqF0pYYYg,_72MGwRTJEd6-CtZFHiHFGA,_qPzHAjtZEd6EJ5PABot5eA"]=true
contentPage.processPage.suppressedItems["_8IT7Ef7cEd2qlKqF0pYYYg,_72MGwRTJEd6-CtZFHiHFGA,_qPzHBTtZEd6EJ5PABot5eA"]=true
contentPage.processPage.suppressedItems["_8IT7Ef7cEd2qlKqF0pYYYg,_72MGwRTJEd6-CtZFHiHFGA,_qPzHBjtZEd6EJ5PABot5eA"]=true
contentPage.processPage.imageFiles["_8IT7Ef7cEd2qlKqF0pYYYg,_zzJygRTLEd6-CtZFHiHFGAActivity"]="./../../practice.mgmt.portfolio_mgmt.base-ibm/deliveryprocesses/resources/monitor_and_control_portfolio_E034D63D_4ee5e3d1_Activity.jpeg"
contentPage.processPage.imageFiles["_8IT7Ef7cEd2qlKqF0pYYYgActivity"]="./../../practice.mgmt.portfolio_mgmt.base-ibm/deliveryprocesses/resources/portf_mgmt_reference_model_81663F40_81663f40_Activity.jpeg"
contentPage.processPage.suppressedItems["_8IT7Ef7cEd2qlKqF0pYYYg,_1dWowDtSEd6EJ5PABot5eA"]=true
contentPage.processPage.suppressedItems["_8IT7Ef7cEd2qlKqF0pYYYg,_qPzHADtZEd6EJ5PABot5eA"]=true
contentPage.processPage.suppressedItems["_8IT7Ef7cEd2qlKqF0pYYYg,_qPzHAjtZEd6EJ5PABot5eA"]=true
contentPage.processPage.suppressedItems["_8IT7Ef7cEd2qlKqF0pYYYg,_1dWoxjtSEd6EJ5PABot5eA"]=true
contentPage.processPage.suppressedItems["_8IT7Ef7cEd2qlKqF0pYYYg,_oIHr0EAaEd6so4MawQGgnA"]=true
contentPage.processPage.suppressedItems["_8IT7Ef7cEd2qlKqF0pYYYg,_qPzHBjtZEd6EJ5PABot5eA"]=true
contentPage.processPage.imageFiles["_8IT7Ef7cEd2qlKqF0pYYYg,_aQ7IcTA1Ed6dhLmEQKbzPgActivity"]="./../../practice.mgmt.portfolio_mgmt.base-ibm/deliveryprocesses/resources/define_portfolio_structures_and_metrics_FE658994_6d169728_Activity.jpeg"
contentPage.processPage.imageFiles["_8IT7Ef7cEd2qlKqF0pYYYg,_6Dz1ERTHEd6-CtZFHiHFGAActivity"]="./../../practice.mgmt.portfolio_mgmt.base-ibm/deliveryprocesses/resources/define_and_prioritize_portfolio_900A7D31_febb8ac5_Activity.jpeg"
contentPage.processPage.suppressedItems["_8IT7Ef7cEd2qlKqF0pYYYg,_6Dz1ERTHEd6-CtZFHiHFGA,_1dWowDtSEd6EJ5PABot5eA"]=true
contentPage.processPage.suppressedItems["_8IT7Ef7cEd2qlKqF0pYYYg,_6Dz1ERTHEd6-CtZFHiHFGA,_1dWoxjtSEd6EJ5PABot5eA"]=true
contentPage.processPage.suppressedItems["_8IT7Ef7cEd2qlKqF0pYYYg,_6Dz1ERTHEd6-CtZFHiHFGA,_oIHr0EAaEd6so4MawQGgnA"]=true
contentPage.processPage.imageFiles["_PKdKUTA1Ed6dhLmEQKbzPgActivity"]="./../../practice.mgmt.portfolio_mgmt.base-ibm/capabilitypatterns/resources/define_portfolio_structures_and_metrics_56BB7882_56bb7882_Activity.jpeg"
contentPage.processPage.imageFiles["_VXWtgRTCEd6-CtZFHiHFGAActivity"]="./../../practice.mgmt.portfolio_mgmt.base-ibm/capabilitypatterns/resources/define_and_prioritize_portfolio_DF433A84_df433a84_Activity.jpeg"
contentPage.processPage.suppressedItems["_VXWtgRTCEd6-CtZFHiHFGA,_1dWowDtSEd6EJ5PABot5eA"]=true
contentPage.processPage.suppressedItems["_VXWtgRTCEd6-CtZFHiHFGA,_1dWoxjtSEd6EJ5PABot5eA"]=true
contentPage.processPage.suppressedItems["_VXWtgRTCEd6-CtZFHiHFGA,_oIHr0EAaEd6so4MawQGgnA"]=true
contentPage.processPage.imageFiles["_2bmi0RTIEd6-CtZFHiHFGAActivity"]="./../../practice.mgmt.portfolio_mgmt.base-ibm/capabilitypatterns/resources/balance_and_authorize_portfolio_63D1B4EE_63d1b4ee_Activity.jpeg"
contentPage.processPage.suppressedItems["_2bmi0RTIEd6-CtZFHiHFGA,_qPzHADtZEd6EJ5PABot5eA"]=true
contentPage.processPage.suppressedItems["_2bmi0RTIEd6-CtZFHiHFGA,_qPzHAjtZEd6EJ5PABot5eA"]=true
contentPage.processPage.suppressedItems["_2bmi0RTIEd6-CtZFHiHFGA,_qPzHBTtZEd6EJ5PABot5eA"]=true
contentPage.processPage.suppressedItems["_2bmi0RTIEd6-CtZFHiHFGA,_qPzHBjtZEd6EJ5PABot5eA"]=true
contentPage.processPage.imageFiles["_hukBIRTKEd6-CtZFHiHFGAActivity"]="./../../practice.mgmt.portfolio_mgmt.base-ibm/capabilitypatterns/resources/monitor_and_control_portfolio_751EA36F_751ea36f_Activity.jpeg"
contentPage.processPage.elementUrls["_ny5NsPv3Ed-HzsN-l08Gjg_S1ofQDswEd6EJ5PABot5eA_fgz2QDBMEd6Utr35iJRrfw"] = ["Market Analysis Report","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/market_analysis_report_456B3646.html"];
contentPage.processPage.elementUrls["_v1hgAfv6Ed-Zy-YVeUJQew_5SuDQC-KEd6C0qOQeF7hUA"] = ["Portfolio Analyst","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/portfolio_analyst_A051DB45.html"];
contentPage.processPage.elementUrls["_LxamoBTFEd6-CtZFHiHFGA"] = ["Select Components","practice.mgmt.portfolio_mgmt.base-ibm/capabilitypatterns/select_components_C555C388.html"];
contentPage.processPage.elementUrls["_qEIJIPv6Ed-Zy-YVeUJQew_5SuDQC-KEd6C0qOQeF7hUA_ayLDUC-QEd6C0qOQeF7hUA"] = ["Components List","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/components_list_FCF689C6.html"];
contentPage.processPage.elementUrls["_wBFvoHWCEd6rrKmNlLhkmQ"] = ["Validated Progress Status","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/validated_progress_status_D289F7FB.html"];
contentPage.processPage.elementUrls["_6Dz1ERTHEd6-CtZFHiHFGA"] = ["Define and Prioritize Portfolio","practice.mgmt.portfolio_mgmt.base-ibm/deliveryprocesses/define_and_prioritize_portfolio_900A7D31.html"];
contentPage.processPage.elementUrls["_mJGlYPv3Ed-HzsN-l08Gjg"] = ["Categorize Components","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/categorize_components.prod_portf_mgmt_DB70D957.html"];
contentPage.processPage.elementUrls["_nKznYBTKEd6-CtZFHiHFGA"] = ["Consolidate Progress and Results","practice.mgmt.portfolio_mgmt.base-ibm/capabilitypatterns/consolidate_progress_and_results_B56D5A9C.html"];
contentPage.processPage.elementUrls["_pTTk8BTKEd6-CtZFHiHFGA"] = ["Analyze Portfolio Trends and Variances","practice.mgmt.portfolio_mgmt.base-ibm/capabilitypatterns/analyze_portfolio_trends_and_variances_12065407.html"];
contentPage.processPage.elementUrls["_hukBIRTKEd6-CtZFHiHFGA"] = ["Monitor and Control Portfolio","practice.mgmt.portfolio_mgmt.base-ibm/capabilitypatterns/monitor_and_control_portfolio_751EA36F.html"];
contentPage.processPage.elementUrls["__Ma4MBTIEd6-CtZFHiHFGA"] = ["Consolidate Supply","practice.mgmt.portfolio_mgmt.base-ibm/capabilitypatterns/consolidate_supply_CAD3D356.html"];
contentPage.processPage.elementUrls["_nX1JsPv0Ed-HzsN-l08Gjg_1AicYC-KEd6C0qOQeF7hUA_CpefsESyEd6Xs8pPM8Zufg"] = ["Portfolio Structure Document","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/portfolio_structure_document_98DDF36F.html"];
contentPage.processPage.elementUrls["_GNDgtxscEd6iF4LVaEfgRw"] = ["Define and Prioritize Portfolio","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/define_and_prioritize_portfolio_D7AA1C51.html"];
contentPage.processPage.elementUrls["_qsNc0Pv6Ed-Zy-YVeUJQew"] = ["Monitor Changes in Conditions","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/monitor_changes_in_conditions.prod_portf_mgmt_856C883C.html"];
contentPage.processPage.elementUrls["_VXWtgRTCEd6-CtZFHiHFGA"] = ["Define and Prioritize Portfolio","practice.mgmt.portfolio_mgmt.base-ibm/capabilitypatterns/define_and_prioritize_portfolio_DF433A84.html"];
contentPage.processPage.elementUrls["_kWD6cPv3Ed-HzsN-l08Gjg"] = ["Identify Components","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/identify_components.prod_portf_mgmt_7068F09.html"];
contentPage.processPage.elementUrls["_RWIF03FeEd61eZ0skzxccQ"] = ["Strategic Business Plan","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/strategic_business_plan_E7039C9D.html"];
contentPage.processPage.elementUrls["_pufMsEAaEd6so4MawQGgnA"] = ["Strategic Business Plan","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/strategic_business_plan_5A93209F.html"];
contentPage.processPage.elementUrls["_aQ7IcTA1Ed6dhLmEQKbzPg"] = ["Define Portfolio Structures and Metrics","practice.mgmt.portfolio_mgmt.base-ibm/deliveryprocesses/define_portfolio_structures_and_metrics_FE658994.html"];
contentPage.processPage.elementUrls["_NcxuMPv6Ed-Zy-YVeUJQew_5SuDQC-KEd6C0qOQeF7hUA_WVRKsEAZEd6so4MawQGgnA"] = ["Ideas and Requests List","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/ideas_and_requests_list_BA7AA895.html"];
contentPage.processPage.elementUrls["_v1hgAvv6Ed-Zy-YVeUJQew"] = ["Monitor the Portfolio and Conduct Reviews","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/monitor_portfolio_and_conduct_reviews.prod_portf_mgmt_AA9A26F4.html"];
contentPage.processPage.elementUrls["_Hn861DA4Ed6dhLmEQKbzPg"] = ["Define Portfolio Structures and Metrics","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/define_portfolio_structures_and_metrics_8B1CE95B.html"];
contentPage.processPage.elementUrls["_nX1JsPv0Ed-HzsN-l08Gjg_WiRwIDswEd6EJ5PABot5eA"] = ["Financial Controller","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/financial_controller_3918F4CE.html"];
contentPage.processPage.elementUrls["_nCUsYPv3Ed-HzsN-l08Gjg_or2ZQDQMEd6QsN5bdDcYQg_NYhApvGBEd2QnaoA1DFTuA"] = ["Product Roadmap","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/product_roadmap_218F6BB5.html"];
contentPage.processPage.elementUrls["_v1hgAvv6Ed-Zy-YVeUJQew_or2ZQDQMEd6QsN5bdDcYQg_0R8fMDtKEd6EJ5PABot5eA"] = ["Business Justification","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/business_justification_483A7B9E.html"];
contentPage.processPage.elementUrls["_ny5NsPv3Ed-HzsN-l08Gjg_or2ZQDQMEd6QsN5bdDcYQg"] = ["Product Manager","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/product_manager_186F36C8.html"];
contentPage.processPage.elementUrls["_qEIJIPv6Ed-Zy-YVeUJQew_5SuDQC-KEd6C0qOQeF7hUA_WVRKsEAZEd6so4MawQGgnA"] = ["Ideas and Requests List","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/ideas_and_requests_list_D570739C.html"];
contentPage.processPage.elementUrls["_YJ65cBsdEd6iF4LVaEfgRw"] = ["Product Roadmap","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/product_roadmap_8CE32693.html"];
contentPage.processPage.elementUrls["_qRcoMBTKEd6-CtZFHiHFGA"] = ["Consolidate Benefits and Revenue Realization","practice.mgmt.portfolio_mgmt.base-ibm/capabilitypatterns/consolidate_benefits_and_revenue_realization_6876C6C4.html"];
contentPage.processPage.elementUrls["_KJtpABTFEd6-CtZFHiHFGA"] = ["Categorize Components","practice.mgmt.portfolio_mgmt.base-ibm/capabilitypatterns/categorize_components_431F5879.html"];
contentPage.processPage.elementUrls["_72MGwRTJEd6-CtZFHiHFGA"] = ["Balance and Authorize Portfolio","practice.mgmt.portfolio_mgmt.base-ibm/deliveryprocesses/balance_and_authorize_portfolio_4135AB31.html"];
contentPage.processPage.elementUrls["_nX1JsPv0Ed-HzsN-l08Gjg_1AicYC-KEd6C0qOQeF7hUA"] = ["Product Portfolio Manager","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/product_portfolio_manager_C7196003.html"];
contentPage.processPage.elementUrls["_rM6K4BTKEd6-CtZFHiHFGA"] = ["Monitor Portfolio and Conduct Reviews","practice.mgmt.portfolio_mgmt.base-ibm/capabilitypatterns/monitor_portfolio_and_conduct_reviews_DA583300.html"];
contentPage.processPage.elementUrls["_BcsRsBTJEd6-CtZFHiHFGA"] = ["Authorize and Assign Components","practice.mgmt.portfolio_mgmt.base-ibm/capabilitypatterns/authorize_and_assign_components_8DAE4A90.html"];
contentPage.processPage.elementUrls["_nCUsYPv3Ed-HzsN-l08Gjg_or2ZQDQMEd6QsN5bdDcYQg_lxgYQDBMEd6Utr35iJRrfw"] = ["Win-Loss Review","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/win_loss_review_42CAC46C.html"];
contentPage.processPage.elementUrls["_nX1JsPv0Ed-HzsN-l08Gjg_1AicYC-KEd6C0qOQeF7hUA_0igjMEAKEd6so4MawQGgnA"] = ["Consolidated Demand List","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/consolidated_demand_list_45C47A7C.html"];
contentPage.processPage.elementUrls["_NcxuMPv6Ed-Zy-YVeUJQew_1AicYC-KEd6C0qOQeF7hUA_0igjMEAKEd6so4MawQGgnA"] = ["Consolidated Demand List","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/consolidated_demand_list_DEA37BB.html"];
contentPage.processPage.elementUrls["_NcxuMPv6Ed-Zy-YVeUJQew_1AicYC-KEd6C0qOQeF7hUA_CpefsESyEd6Xs8pPM8Zufg"] = ["Portfolio Structure Document","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/portfolio_structure_document_6103B0AE.html"];
contentPage.processPage.elementUrls["_TEq9IDA1Ed6dhLmEQKbzPg"] = ["Define Portfolio Structures and Metrics","practice.mgmt.portfolio_mgmt.base-ibm/capabilitypatterns/define_portf_structures_and_metrics_31052BB5.html"];
contentPage.processPage.elementUrls["_OzHXkBscEd6iF4LVaEfgRw"] = ["Monitor and Control Portfolio","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/monitor_and_control_portfolio_DAB7FB55.html"];
contentPage.processPage.elementUrls["_OFTt0Pv6Ed-Zy-YVeUJQew__QDLsDQcEd6QsN5bdDcYQg"] = ["Production Manager","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/production_manager_174E796E.html"];
contentPage.processPage.elementUrls["_qEIJIPv6Ed-Zy-YVeUJQew_5SuDQC-KEd6C0qOQeF7hUA_LS0qMHV9Ed6rrKmNlLhkmQ"] = ["Threats and Opportunities Analysis","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/threats_and_opportunities_analysis_F1E73D39.html"];
contentPage.processPage.elementUrls["_YJ65cRsdEd6iF4LVaEfgRw"] = ["Technology Roadmap","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/technology_roadmap_978106A3.html"];
contentPage.processPage.elementUrls["_nX1JsPv0Ed-HzsN-l08Gjg"] = ["Define Portfolio Structures and Metrics","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/define_portf_structures_and_metrics.prod_portf_mgmt_C309519B.html"];
contentPage.processPage.elementUrls["_o6H7gPv3Ed-HzsN-l08Gjg_sm_W8DtQEd6EJ5PABot5eA"] = ["Portfolio Review Board","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/portfolio_review_board_FD678AD1.html"];
contentPage.processPage.elementUrls["_nX1JsPv0Ed-HzsN-l08Gjg_S1ofQDswEd6EJ5PABot5eA_i4lDUDBMEd6Utr35iJRrfw"] = ["Competitive Analysis","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/competitive_analysis_D0DE5668.html"];
contentPage.processPage.elementUrls["_kWD6cPv3Ed-HzsN-l08Gjg_5SuDQC-KEd6C0qOQeF7hUA_WVRKsEAZEd6so4MawQGgnA"] = ["Ideas and Requests List","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/ideas_and_requests_list_592BD844.html"];
contentPage.processPage.elementUrls["_kWD6cPv3Ed-HzsN-l08Gjg_5SuDQC-KEd6C0qOQeF7hUA_xLRFIEALEd6so4MawQGgnA"] = ["Portfolio Recommendations","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/portfolio_recommendations_42C7E50.html"];
contentPage.processPage.elementUrls["_NcxuMPv6Ed-Zy-YVeUJQew_5SuDQC-KEd6C0qOQeF7hUA_xLRFIEALEd6so4MawQGgnA"] = ["Portfolio Recommendations","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/portfolio_recommendations_657B4EA1.html"];
contentPage.processPage.elementUrls["_mJGlYPv3Ed-HzsN-l08Gjg_1AicYC-KEd6C0qOQeF7hUA_ayLDUC-QEd6C0qOQeF7hUA"] = ["Components List","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/components_list_B1F18347.html"];
contentPage.processPage.elementUrls["_mJGlYPv3Ed-HzsN-l08Gjg_1AicYC-KEd6C0qOQeF7hUA_CpefsESyEd6Xs8pPM8Zufg"] = ["Portfolio Structure Document","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/portfolio_structure_document_C4E5522B.html"];
contentPage.processPage.elementUrls["_nCUsYPv3Ed-HzsN-l08Gjg_or2ZQDQMEd6QsN5bdDcYQg_0R8fMDtKEd6EJ5PABot5eA"] = ["Business Justification","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/business_justification_585FCC92.html"];
contentPage.processPage.elementUrls["_QQCgAPv6Ed-Zy-YVeUJQew_sm_W8DtQEd6EJ5PABot5eA"] = ["Portfolio Review Board","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/portfolio_review_board_1F9D75D6.html"];
contentPage.processPage.elementUrls["_mJGlYPv3Ed-HzsN-l08Gjg_1AicYC-KEd6C0qOQeF7hUA_7aecYDsvEd6EJ5PABot5eA"] = ["Portfolio Constraints and Metrics Document","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/portfolio_constraints_and_metrics_doc_1EF98DE2.html"];
contentPage.processPage.elementUrls["_Mb344BTFEd6-CtZFHiHFGA"] = ["Prioritize Components","practice.mgmt.portfolio_mgmt.base-ibm/capabilitypatterns/prioritize_components_7F12FEE1.html"];
contentPage.processPage.elementUrls["_v1hgAvv6Ed-Zy-YVeUJQew_or2ZQDQMEd6QsN5bdDcYQg_NYhApvGBEd2QnaoA1DFTuA"] = ["Product Roadmap","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/product_roadmap_116A1AC1.html"];
contentPage.processPage.elementUrls["_ny5NsPv3Ed-HzsN-l08Gjg_S1ofQDswEd6EJ5PABot5eA_i4lDUDBMEd6Utr35iJRrfw"] = ["Competitive Analysis","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/competitive_analysis_33EC2C4C.html"];
contentPage.processPage.elementUrls["_ny5NsPv3Ed-HzsN-l08Gjg_S1ofQDswEd6EJ5PABot5eA"] = ["Marketing Manager","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/marketing_mgr_E2C2CA0.html"];
contentPage.processPage.elementUrls["_-nwr8BTIEd6-CtZFHiHFGA"] = ["Consolidate Demand","practice.mgmt.portfolio_mgmt.base-ibm/capabilitypatterns/consolidate_demand_BBA19246.html"];
contentPage.processPage.elementUrls["_ny5NsPv3Ed-HzsN-l08Gjg_1AicYC-KEd6C0qOQeF7hUA"] = ["Product Portfolio Manager","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/product_portfolio_manager_BE255A9F.html"];
contentPage.processPage.elementUrls["_OFTt0Pv6Ed-Zy-YVeUJQew_5wKGAFAhEeCk-Pay6xRCzA"] = ["Team Lead","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/team_lead_381B65CA.html"];
contentPage.processPage.elementUrls["_v1hgAvv6Ed-Zy-YVeUJQew_or2ZQDQMEd6QsN5bdDcYQg"] = ["Product Manager","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/product_manager_A03D72B3.html"];
contentPage.processPage.elementUrls["_K-J9sBTFEd6-CtZFHiHFGA"] = ["Evaluate Components","practice.mgmt.portfolio_mgmt.base-ibm/capabilitypatterns/evaluate_components_A2186DD.html"];
contentPage.processPage.elementUrls["_nX1JsPv0Ed-HzsN-l08Gjg_1AicYC-KEd6C0qOQeF7hUA_7aecYDsvEd6EJ5PABot5eA"] = ["Portfolio Constraints and Metrics Document","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/portfolio_constraints_and_metrics_doc_F2F22F26.html"];
contentPage.processPage.elementUrls["_I40B0BTFEd6-CtZFHiHFGA"] = ["Identify Components","practice.mgmt.portfolio_mgmt.base-ibm/capabilitypatterns/identify_components_97A4442C.html"];
contentPage.processPage.elementUrls["_qEIJIPv6Ed-Zy-YVeUJQew"] = ["Consolidate Progress and Results","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/consolidate_progress_and_results.prod_portf_mgmt_D862C461.html"];
contentPage.processPage.elementUrls["_PKdKUTA1Ed6dhLmEQKbzPg"] = ["Define Portfolio Structures and Metrics","practice.mgmt.portfolio_mgmt.base-ibm/capabilitypatterns/define_portfolio_structures_and_metrics_56BB7882.html"];
contentPage.processPage.elementUrls["_qEIJIPv6Ed-Zy-YVeUJQew_5SuDQC-KEd6C0qOQeF7hUA_xLRFIEALEd6so4MawQGgnA"] = ["Portfolio Recommendations","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/portfolio_recommendations_807119A8.html"];
contentPage.processPage.elementUrls["_PHUkcPv6Ed-Zy-YVeUJQew_1AicYC-KEd6C0qOQeF7hUA"] = ["Product Portfolio Manager","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/product_portfolio_manager_ADE1C01E.html"];
contentPage.processPage.elementUrls["_N8IFMBscEd6iF4LVaEfgRw"] = ["Balance and Authorize Portfolio","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/balance_and_authorize_portfolio_7D516C9F.html"];
contentPage.processPage.elementUrls["_QQCgAPv6Ed-Zy-YVeUJQew_5SuDQC-KEd6C0qOQeF7hUA"] = ["Portfolio Analyst","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/portfolio_analyst_59B3571.html"];
contentPage.processPage.elementUrls["_QQCgAPv6Ed-Zy-YVeUJQew_JkGD0DQcEd6QsN5bdDcYQg"] = ["Resource Manager","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/resource_mgr_7FD43A39.html"];
contentPage.processPage.elementUrls["_NcxuMPv6Ed-Zy-YVeUJQew_5SuDQC-KEd6C0qOQeF7hUA_LS0qMHV9Ed6rrKmNlLhkmQ"] = ["Threats and Opportunities Analysis","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/threats_and_opportunities_analysis_D6F17232.html"];
contentPage.processPage.elementUrls["_oOAw0BTKEd6-CtZFHiHFGA"] = ["Monitor Changes in Conditions","practice.mgmt.portfolio_mgmt.base-ibm/capabilitypatterns/monitor_changes_in_conditions_9AEE68EA.html"];
contentPage.processPage.elementUrls["_PHUkcPv6Ed-Zy-YVeUJQew"] = ["Optimize Portfolio","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/optimize_portfolio.prod_portf_mgmt_FC4E33E0.html"];
contentPage.processPage.elementUrls["_v1hgAvv6Ed-Zy-YVeUJQew_sm_W8DtQEd6EJ5PABot5eA"] = ["Portfolio Review Board","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/portfolio_review_board_2C33299A.html"];
contentPage.processPage.elementUrls["_nX1JsPv0Ed-HzsN-l08Gjg_S1ofQDswEd6EJ5PABot5eA_fgz2QDBMEd6Utr35iJRrfw"] = ["Market Analysis Report","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/market_analysis_report_E25D6062.html"];
contentPage.processPage.elementUrls["_NcxuMPv6Ed-Zy-YVeUJQew_1AicYC-KEd6C0qOQeF7hUA_7aecYDsvEd6EJ5PABot5eA"] = ["Portfolio Constraints and Metrics Document","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/portfolio_constraints_and_metrics_doc_BB17EC65.html"];
contentPage.processPage.elementUrls["_Fnf5YRsYEd6iF4LVaEfgRw"] = ["Product Portfolio Management Reference Model","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/prod_portf_mgmt_reference_model_454E7EC9.html"];
contentPage.processPage.elementUrls["_OFTt0Pv6Ed-Zy-YVeUJQew_JkGD0DQcEd6QsN5bdDcYQg_55yHEDQbEd6QsN5bdDcYQg"] = ["Resources List","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/resources_list_FA5F02F7.html"];
contentPage.processPage.elementUrls["_qEIJIPv6Ed-Zy-YVeUJQew_5SuDQC-KEd6C0qOQeF7hUA_md2dMDtKEd6EJ5PABot5eA"] = ["Component Description","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/component_description_2B4BEAC2.html"];
contentPage.processPage.elementUrls["__7hZ4BTIEd6-CtZFHiHFGA"] = ["Optimize Portfolio","practice.mgmt.portfolio_mgmt.base-ibm/capabilitypatterns/optimize_portfolio_60270478.html"];
contentPage.processPage.elementUrls["_NcxuMPv6Ed-Zy-YVeUJQew_5SuDQC-KEd6C0qOQeF7hUA_md2dMDtKEd6EJ5PABot5eA"] = ["Component Description","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/component_description_10561FBB.html"];
contentPage.processPage.elementUrls["_8IT7Ef7cEd2qlKqF0pYYYg"] = ["Portfolio Management Reference Model","practice.mgmt.portfolio_mgmt.base-ibm/deliveryprocesses/portf_mgmt_reference_model_81663F40.html"];
contentPage.processPage.elementUrls["_OFTt0Pv6Ed-Zy-YVeUJQew"] = ["Consolidate Supply","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/consolidate_supply.prod_portf_mgmt_86E21B7C.html"];
contentPage.processPage.elementUrls["_QQCgAPv6Ed-Zy-YVeUJQew"] = ["Authorize and Assign Components","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/authorize_and_assign_components.prod_portf_mgmt_58C9EE38.html"];
contentPage.processPage.elementUrls["_v1hgAvv6Ed-Zy-YVeUJQew_or2ZQDQMEd6QsN5bdDcYQg_lxgYQDBMEd6Utr35iJRrfw"] = ["Win-Loss Review","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/win_loss_review_32A57378.html"];
contentPage.processPage.elementUrls["_ny5NsPv3Ed-HzsN-l08Gjg"] = ["Select Components","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/select_components.prod_portf_mgmt_4584167F.html"];
contentPage.processPage.elementUrls["_ny5NsPv3Ed-HzsN-l08Gjg_WiRwIDswEd6EJ5PABot5eA"] = ["Financial Controller","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/financial_controller_3024EF6A.html"];
contentPage.processPage.elementUrls["_mJGlYPv3Ed-HzsN-l08Gjg_1AicYC-KEd6C0qOQeF7hUA_0igjMEAKEd6so4MawQGgnA"] = ["Consolidated Demand List","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/consolidated_demand_list_71CBD938.html"];
contentPage.processPage.elementUrls["_nX1JsPv0Ed-HzsN-l08Gjg_S1ofQDswEd6EJ5PABot5eA"] = ["Marketing Manager","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/marketing_mgr_17203204.html"];
contentPage.processPage.elementUrls["_ny5NsPv3Ed-HzsN-l08Gjg_5SuDQC-KEd6C0qOQeF7hUA"] = ["Portfolio Analyst","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/portfolio_analyst_8A62AD4A.html"];
contentPage.processPage.elementUrls["_v1hgAvv6Ed-Zy-YVeUJQew_or2ZQDQMEd6QsN5bdDcYQg_3LUgEDtKEd6EJ5PABot5eA"] = ["Business Case","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/busines_case_76A68401.html"];
contentPage.processPage.elementUrls["_nCUsYPv3Ed-HzsN-l08Gjg"] = ["Evaluate Components","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/evaluate_components.prod_portf_mgmt_544A42E8.html"];
contentPage.processPage.elementUrls["_zzJygRTLEd6-CtZFHiHFGA"] = ["Monitor and Control Portfolio","practice.mgmt.portfolio_mgmt.base-ibm/deliveryprocesses/monitor_and_control_portfolio_E034D63D.html"];
contentPage.processPage.elementUrls["_wBFvonWCEd6rrKmNlLhkmQ"] = ["Validated Revenue and Benefits Status","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/validated_revenue_benefits_status_CBC0EC21.html"];
contentPage.processPage.elementUrls["_kWD6cPv3Ed-HzsN-l08Gjg_5SuDQC-KEd6C0qOQeF7hUA_md2dMDtKEd6EJ5PABot5eA"] = ["Component Description","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/component_description_AF074F6A.html"];
contentPage.processPage.elementUrls["_NcxuMPv6Ed-Zy-YVeUJQew"] = ["Consolidate Demand","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/consolidate_demand.prod_portf_mgmt_12A3551A.html"];
contentPage.processPage.elementUrls["_v1hgAfv6Ed-Zy-YVeUJQew"] = ["Consolidate Benefits and Revenue Realization","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/consolidate_benefits_and_revenue_realization.prod_portf_mgmt_9FFC46E4.html"];
contentPage.processPage.elementUrls["_OFTt0Pv6Ed-Zy-YVeUJQew_0a0o0MlgEdmt3adZL5Dmdw"] = ["Project Manager","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/project_manager_FC08B23A.html"];
contentPage.processPage.elementUrls["_nX1JsPv0Ed-HzsN-l08Gjg_1AicYC-KEd6C0qOQeF7hUA_ayLDUC-QEd6C0qOQeF7hUA"] = ["Components List","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/components_list_85EA248B.html"];
contentPage.processPage.elementUrls["_kWD6cPv3Ed-HzsN-l08Gjg_5SuDQC-KEd6C0qOQeF7hUA_LS0qMHV9Ed6rrKmNlLhkmQ"] = ["Threats and Opportunities Analysis","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/threats_and_opportunities_analysis_75A2A1E1.html"];
contentPage.processPage.elementUrls["_v1hgAPv6Ed-Zy-YVeUJQew"] = ["Analyze Portfolio Trends and Variances","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/analyze_portfolio_trends_and_variances.prod_portf_mgmt_B16332CE.html"];
contentPage.processPage.elementUrls["_nCUsYPv3Ed-HzsN-l08Gjg_or2ZQDQMEd6QsN5bdDcYQg_3LUgEDtKEd6EJ5PABot5eA"] = ["Business Case","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/busines_case_86CBD4F5.html"];
contentPage.processPage.elementUrls["_NcxuMPv6Ed-Zy-YVeUJQew_5SuDQC-KEd6C0qOQeF7hUA_ayLDUC-QEd6C0qOQeF7hUA"] = ["Components List","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/components_list_E200BEBF.html"];
contentPage.processPage.elementUrls["_2bmi0RTIEd6-CtZFHiHFGA"] = ["Balance and Authorize Portfolio","practice.mgmt.portfolio_mgmt.base-ibm/capabilitypatterns/balance_and_authorize_portfolio_63D1B4EE.html"];
contentPage.processPage.elementUrls["_o6H7gPv3Ed-HzsN-l08Gjg"] = ["Prioritize Components","practice.mgmt.product_portfolio_mgmt.base-ibm/deliveryprocesses/prioritize_components.prod_portf_mgmt_FFDF179D.html"];
